[package]
name = "rustycheckers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
crate-type = ["cdylib"]

[dependencies]
mut_static = { version="5.0.0" }
lazy_static = { version="1.0.2" }
