[package]
name = "wasmchat"
version = "0.1.0"
authors = ["Kevin Hoffman <your@address.com>"]

[dependencies]
web_logger = "0.1"
log = "0.4"
strum = "0.9"
strum_macros = "0.9"
serde = "1"
serde_json = "1"
serde_derive = "1"
stdweb = "0.4.8"
yew = "0.4.0"